# Hur gör jag... {#faq}

Här hittar du:

- Frågor från studenter
- Frågor om statistik och SPSS
- Tips på vidare läsning

## Statistik

### Vad är sambandsmått?

Sambandsmått, eller korrelationsmått, är ett mått på sambandet mellan två variabler. Det innebär att två variabler samvarierar med varandra. Till exempel samvarierar vikt och längd. Ju längre man är, desto tyngre är man.

Videor om korrelation:

- [What Is Correlation? (6 min)](https://www.youtube.com/watch?v=Ypgo4qUBt5o)
- [Statistics 101: Understanding Correlation (27 min)](https://www.youtube.com/watch?v=4EXNedimDMs)

### Vilket sambandsmått ska jag välja?

Det är variabelns skalnivå som avgör vilket sambandsmått du ska använda.

- Om båda variablerna är på nominalskalenivå: Cramérs V.
- Om båda variablerna är på ordinalskalenivå: Spearmans rho, Kendalls tau-b/tau-c.
- Om båda variablerna är på intervallskalenivå: Pearsons r.
- Om variablerna har olika skalnivåer: Utgå från den minsta skalnivån.

Om du har variablerna kön (man/kvinna) och inkomst (i kronor) har kön den minsta skalnivån. Kön är då på nominalskalenivå och inkomst på intervallskalenivå. Därmed bör du välja Cramérs V.

[![Vilket sambandsmått ska jag välja? Ett flödesschema som underlättar valet och tolkningen av olika sambandsmått.
](images/valja-sambandsmatt.png)](images/valja-sambandsmatt.png)

### Hur tolkar jag sambandsmått?

Det är ämneskunskap som framför allt bör guida tolkningen av sambandsmått. Om du saknar ämneskunskap har @cohen_statistical_1988 gett riktlinjer för Pearsons r, Cramérs V med flera:

- 0,10 = litet samband
- 0,30 = medelstort samband
- 0,50 = stort samband

Pearsons r varierar från -1 till +1. Cramérs V kan bara variera från 0 till 1 eftersom det är på nominalskalenivå.

Sambandsmått i samhällsvetenskap är oftast ganska små, vilket framgår av graferna nedan. De visar att det genomsnittliga samabandsmåttet inom socialpsykologi är r = 0,21 och är baserad på 25 000 studier med 8 miljoner människor över 100 år [@richard_one_2003]. Samma sak syns i 60 år av kommunikationsforskning som bygger på över 9 500 studier och 8,7 miljoner människor där medelvärdet också är r = 0,21 [@rains_sixty_2018].

```{r effect-sizes, fig.height=8}
df <- read.csv("data/soc-psych.tsv", header=TRUE, sep="\t", stringsAsFactors=FALSE)
df2 <- read.csv("data/effectsizes-comm.csv", header=TRUE, sep=",", stringsAsFactors=FALSE)

library(tidyverse)
library(gridExtra)

# Reproduce graph in Richard et al. (2003), but use density instead.
gg1 <- df %>% ggplot(aes(r)) +
  geom_density(fill="grey") + 
  scale_x_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  labs(title="Sambandsmått från 100 år av socialpsykologi",
       x="Genomsnittlig korrelation",
       y="Densitet")

gg2 <- df2 %>% ggplot(aes(r)) +
  geom_density(fill="grey") + 
  scale_x_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  labs(title="Sambandsmått från 60 år av kommunikationsforskning",
       x="Genomsnittlig korrelation",
       y="Densitet")

grid.arrange(gg1, gg2, nrow=2)
```

### Vad är skillnaden mellan Phi och Cramérs V?

Phi kan du ignorera helt och hållet. Titta bara på Cramérs V.

Phi är ett sambandsmått som endast fungerar för korstabeller med storleken 2 x 2 med två binära variabler. Cramérs V fungerar däremot på alla storlekar av korstabeller.

### Vad är p-värden och statistisk signifikans?

P-värdet visar sannolikheten att få ett resultat som är så extremt (eller mer extremt), givet att nollhypotesen är sann. P-värdet går från 0 till 1.

Läs mer: **[P-värden och hur man tolkar dem](#p-values)**

## SPSS {#faq-spss}

### Var hittar jag p-värdet i SPSS?

Titta i kolumnen *Approximate Significance* (*Approx. Sig.*) eller bara *Sig*.

### Hur analyserar jag en fråga som är kodad på flera variabler?

Låt säga att du har kodat en nyhetsartikel för att se vilka aktörer som förekommer i texten. Varje aktör kan då kodas så att de blir en egen variabel, exempelvis:

- Förekommer politiker? Ja=1 Nej=0
- Förekommer journalister? Ja=1 Nej=0
- Förekommer medborgare? Ja=1 Nej=0

Hur analyserar man detta med en frekvenstabell eller korstabell?

I SPSS kan du använda verktyget `Analyze` > `Tables` > `Custom Tables`. Du kan också använda verktyget `Analyze` > `Multiple Response`. Se länkarna nedan.

- [Analysis Multiple response question (dichotomies)](http://helpdeskspssabs.femplaza.nl/analysis/analysis_multiple_response_dich.htm)
- [Analysis Multiple response question (categories)](http://helpdeskspssabs.femplaza.nl/analysis/analysis_multiple_response_cat.htm)

### Hur summerar jag en rad?

Du har exempelvis kodat hur många gånger ett ord förekommer i en artikel. Analysenheten är artikel och det finns en variabel för hur många gånger ordet förekommer i varje artikel. Nu vill du veta hur många gånger ordet förekommer totalt, beroende på vad det är för artikel (om den förekommer i morgontidning eller kvällstidning). Du har alltså två variabler: (1) antal förekomster av ordet samt (2) typ av tidning.

Gör så här:

1. I SPSS-menyn, välj `Analyze` > `Reports` > `Report Summaries in Columns`.

2. Lägg variabeln du vill summera (variabeln med antal ord) i `Data Column Variables`.

3. Lägg variabeln du vill gruppera analysenheterna efter (variabeln med typ av tidning) i kolumnen `Break Column Variables`.

## Vilka viktiga begrepp bör jag känna till?

|Begrepp|Beskrivning|
|-------|---------------------------------|
|begreppsvaliditet||
|Chi^2^||
|Cramérs V||
|deskriptiv statistik||
|extern validitet||
|felmarginal||
|hypotes||
|intern validitet||
|kausalitet||
|Kendalls tau-b/tau-c||
|korrelation||
|korstabell||
|kvartil||
|medelvärde||
|median||
|modalprocent||
|normaldistribution||
|operationalisering||
|operationell definition||
|p-värde||
|Pearsons r||
|population||
|reliabilitet||
|resultatvaliditet (eller *statistisk inferensvaliditet*)||
|sambandsmått||
|sampel||
|skalnivå||
|Spearmans rho||
|standardavvikelse||
|statistisk signifikans||
|teoretisk definition||
|typvärde||
|validitet||
|variabel||
|variationsvidd||