# Kolumnprocent och radprocent i korstabeller {#crosstabs-percent}

Här hittar du:

- Skillnaden mellan kolumnprocent, radprocent och totalprocent
- Hur du bör utforma korstabeller

## Rådata

Tabellen nedan är en korstabell med två variabler (kön och rädd) som båda har två variabelvärden (kvinnor/män respektive rädd/orädd). Här ser vi alltså att det finns 426 personer, varav 298 är kvinnor och 128 är män. Samtidigt är 330 personer rädda medan 96 personer är orädda.

| | Kvinnor | Män | Totalt
| --------- | :---------: | :---------: | :---------:
| Rädd | 223 | 107 | 330
| Orädd | 75 | 21 | 96
| Totalt | 298 | 128 | 426

Table: Antalet personer.

## Tre typer av procent i tabeller

### Kolumnprocent

En tabell med kolumnprocent måste läsas kolumnvis. Kolumnprocent svarar på frågan "hur stor andel av *kvinnorna* är rädda?". Svar: 75%. Man ser om en tabell har kolumnprocent om man kan addera alla procenttal i kolumnen så att de blir 100 (75 + 25 = 100 respektive 84 + 16 = 100). Kolumnprocent gör att vi kan jämföra kvinnor med män (för att se vilka som är mest rädda).

| | Kvinnor | Män
| --------- | :---------: | :---------:
| Rädd | **75** | 84
| Orädd | **25** | 16
| Totalt | **100 (n = 298)** | 100 (n = 128)

Table: Kolumnprocent: värdena i kolumnen används som bas för procenttalen.

### Radprocent

En tabell med radprocent måste läsas radvis. Radprocent svarar på frågan "hur stor andel av *de rädda* är kvinnor?". Svar: 68%. Man ser om en tabell har radprocent om man kan addera alla procenttal på raden så att de blir 100 (68 + 32 = 100 respektive 78 + 22 = 100). Radprocent gör att vi kan jämföra rädda med orädda (för att se om de är kvinnor eller män).

| | Kvinnor | Män | Totalt
| --------- | :---------: | :---------: | :---------:
| Rädd | **68** | **32** | **100 (n = 330)**
| Orädd | 78 | 22 | 100 (n = 96)

Table: Radprocent: värdena i raden används som bas för procenttalen.

### Totalprocent

En tabell med totalprocent måste läsas cellvis. Totalprocent svarar på frågan "hur stor andel av *alla* är rädda kvinnor?". Svar: 52%. Man ser om en tabell har totalprocent om man kan addera alla procenttal så att de blir 100 (52 + 18 + 25 + 5 = 100). Totalprocent gör att vi kan jämföra alla fyra grupper med varandra. De fyra grupperna är rädda kvinnor, rädda män, orädda kvinnor samt orädda män.

| | Kvinnor | Män | Totalt
| --------- | :---------: | :---------: | :---------:
| Rädd | **52** | **25** | 
| Orädd | **18** | **5** | 
| Totalt | | | **100 (n = 426)** 

Table: Totalprocent: värdena i alla celler används som bas för procenttalen.

### Att tänka på när du skapar tabeller

- Använd procent i tabellen. Det gör att man kan jämföra två grupper med varandra trots att de har olika antal observationer.
- Ange antalet observationer (n) i tabellen så att man vet basen för procenttalen.
- Summera tabellen till 100% (med kolumnprocent, radprocent eller totalprocent) så att det framgår hur tabellen ska tolkas.
- Tumregel: lägg den oberoende variabeln i kolumnen (och den beroende variabeln på raden) och använd kolumnprocent. 
- Totalprocent bör undvikas.
- Tabeller bör ha ett nummer som identifierar tabellen (Tabell 1, Tabell 2, Tabell 3 och så vidare), en rubrik ovanför tabellen, samt en eventuell kommentar under tabellen.
- Summera procent till heltal (50% i stället för 49,7%). I samhällsvetenskap behöver vi ofta inte så stor precision i antal decimaler. Om man använder heltal så kan den summerade radprocenten eller kolumnprocenten bli 101. Skriv då en kommentar och säg att det beror på avrundning.

## Se också

- Nedladdningsbar fil med kolumnprocent, radprocent och totalprocent: [korstabell.xlsx](/filer/korstabell.xlsx)