# Resurser

Här hittar du:

- [Dataset](#dataset) och forskningsdatabaser på nätet du kan ladda ned och använda
- [Program](#program) du kan ladda ned och använda
- [Filer](#files) för färdiga diagram i Excel
- [Länkar](#links) till tips, råd och artiklar om forskning
- [Böcker](#books) för vidare läsning och fördjupning

## Dataset {#dataset}

### Forskningsdata

Lagrar och arkiverar forskningsdata

- [Svensk nationell datatjänst (SND)](https://snd.gu.se/)
- [Consortium of European Social Science Data Archives (CESSDA)](http://cessda.net/)
- [Inter-university Consortium for Political and Social Research (ICPSR)](http://www.icpsr.umich.edu/icpsrweb/ICPSR/index.jsp)

Sökmotorer för forskningsdata

- [re3data.org](http://www.re3data.org/)
- [Metadata Search](http://search.datacite.org/ui)

Psykologi

- [Open Stats Lab](https://sites.trinity.edu/osl) har data från psykologiska studier som är tänkt att användas i undervisning.

### Surveyundersökningar

- [SOM-undersökningen 1986–](https://snd.gu.se/sv/catalogue/search/SOM) (Sverige)
- [The General Social Survey 1972–](http://gss.norc.org/) (USA)
- [Latin American Public Opinion Project](https://www.vanderbilt.edu/lapop/raw-data.php) (Hela Amerika)

### Big Data

- [GDELT Project](http://gdeltproject.org/) - strävar efter att samla alla händelser i massmedierna och har i nuläget en kvarts miljard händelser. Kan också [analyseras i Google BigQuery](https://bigquery.cloud.google.com/table/gdelt-bq:full.events).
- [Google BigQuery](https://cloud.google.com/bigquery/) - verktyg för att analysera big data utvecklat av Google.

### Hitta fler datamängder

- [Öppna Data](https://oppnadata.se/) - katalog från Riksarkivet som hjälper dig hitta öppna data från Sverige
- [Awesome Public Datasets](https://github.com/caesar0301/awesome-public-datasets)

### Välfärdsstatistik

Lista med välfärdsstatistik ursprungligen skapad av [Richard Öhrvall](https://richardohrvall.com/2016/01/databaser-kring-valfardsstatistik/). Kopierad hit därför att Richards hemsida inom kort läggs ned.

Policy Structures

- [Social Citizenship Indicators Data (see Esping-Andersen), Child Benefits Database, SAMIP,  Comparative Welfare state database](http://www.lisdatacenter.org/resources/other-databases/)
- [CWED 2 –- measures of welfare generosity](http://cwed2.org)
- [EU MISSOC](http://ec.europa.eu/social/main.jsp?catId=815&langId=en)
- [Social Security Around the World](https://www.ssa.gov/policy/docs/progdesc/ssptw/)
- [OECD – Taxes and Benefits](http://www.oecd.org/els/soc/benefitsandwagestax-benefitcalculator.htm)
- [Comparative Family Policy Database](http://www.demogr.mpg.de/cgi-bin/databases/fampoldb/index.plx)
- [MIPEX migration data (some on entitlement to benefits)](http://www.mipex.eu)

Expenditure

- [OECD – Social Expenditures Database  (see also OECD health and education datasets)](http://www.oecd.org/social/expenditure.htm)

Income Inequality, Poverty and Living Conditions

- [Luxembourg Income Study](http://www.lisdatacenter.org)
- [World Top incomes database](http://topincomes.parisschoolofeconomics.eu)
- [Standardized World Income Inequality Database](http://myweb.uiowa.edu/fsolt/swiid/swiid.html)
- [Our world in data (historical and world inequality data)](http://ourworldindata.org)
- [EU-SILC](http://ec.europa.eu/eurostat/web/income-and-living-conditions/overview)

Political Institutions, Government Control and Parties

- [Comparative Political Datasets](http://www.cpds-data.org/index.php)
- [Quality of Government Datasets](http://qog.pol.gu.se/data/datadownloads) (Göteborgs universitet)

Political Parties

- [Chapel Hill Expert Survey (party positioning as ranked by experts)](http://chesdata.eu)
- [Comparative Manifesto Data (party positioning/salience by manifestos)](https://manifestoproject.wzb.eu)

Labour Market and Wage Bargaining

- [ICTWSS – Wage Bargaining institutions](http://www.uva-aias.net/208)
- [OECD – Employment Protection Legislation](http://www.oecd.org/employment/emp/oecdindicatorsofemploymentprotection.htm)
- [EU – Labor Force Survey](http://ec.europa.eu/eurostat/web/microdata/european-union-labour-force-survey)

Public Attitudes – Cross-National Surveys

- [European Social Survey](http://www.europeansocialsurvey.org)
- [International Social Survey Programme (ISSP)](http://www.gesis.org/en/issp/home/)
- [European Values Survey](http://www.europeanvaluesstudy.eu)
- [World Values Survey](http://www.worldvaluessurvey.org/)
- [Comparative Study of Electoral Systems](http://www.cses.org)

## Program {#program}

### Analysera sociala medier

- [Tools for media and communication research](https://github.com/peterdalle/mediacommtools)
- [EchoSec](https://www.echosec.net/) - sökmotor utifrån geografisk plats (Facebook, Twitter, Pinterest m.fl.).
- [Gephi](https://gephi.org/) - Gephi is the leading visualization and exploration software for all kinds of graphs and networks.
- [NetVizz](https://apps.facebook.com/netvizz/) - grupper eller sidor på Facebook
- [Tweetbeaver](https://tweetbeaver.com/) - många små funktioner för att samla in data från Twitter (convert @name to ID, check if two accounts follow each other, download a user's favorites, search within a user's favorites, download a user's timeline etc.)

Videor:

- [NetVizz - instruktion på svenska (13 min)](https://www.youtube.com/watch?v=S7ZIIe5AqcE)
- [Gephi - instruktion på svenska (9 min)](https://www.youtube.com/watch?v=4_XL_ZXpMgw)

Länktips:

- [Digital Methods Iniative (DMI): Tool database](https://wiki.digitalmethods.net/Dmi/ToolDatabase) har en bra lista över verktyg.
- [Using Twitter as a data source: an overview of social media research tools (updated for 2017)](http://blogs.lse.ac.uk/impactofsocialsciences/2017/05/08/using-twitter-as-a-data-source-an-overview-of-social-media-research-tools-updated-for-2017/)
- [Using Google Trends data for research? Here are 6 questions to ask](https://medium.com/@pewresearch/using-google-trends-data-for-research-here-are-6-questions-to-ask-a7097f5fb526)

### Kartor

- [QGIS](http://www.qgis.org/) - free and open source geographic information system.

### Konvertera data

- [Mr. Data Converter](https://shancarter.github.io/mr-data-converter/) - I will convert your Excel data into one of several web-friendly formats, including HTML, JSON and XML.

### Grafer och diagram {#program-dataviz}

Program för att rita boxar och pilar. Användbart för att rita modeller av olika slag, som statistiska modeller och [SEM](https://en.wikipedia.org/wiki/Structural_equation_modeling).

- [Dia](http://dia-installer.de/) is a program to draw structured diagrams.

### Statistik och dataanalys {#statsprogram}

Medan traditionella statistikprogram som [SPSS](https://www.ibm.com/analytics/se/sv/technology/spss/), [Stata](http://www.stata.com/) och [SAS](http://www.sas.com/) kostar pengar, finns det en hel del gratisalternativ:

- [Data Explorer](http://www.data-explorer.com/)
- [Tableau](http://www.tableau.com/) - notera att Tableau har en akademisk licens som innebär att du kan använda fullversionen som student. Annars har de en gratisversion.
- [GNU PSPP](http://www.gnu.org/software/pspp/) ser ut och fungerar ungefär som SPSS, men är gratis. Kan också läsa SPSS-filer.
- [R](https://www.r-project.org/) är ett programmeringsspråk för statistik.
- [JASP](https://jasp-stats.org/download/) är byggt ovanpå R med de flesta vanliga funktioner inklusive bayesiansk statistik.
- [Jamovi](https://www.jamovi.org/) är en vidareutveckling av JASP med lite annat fokus.

Avancerad statistik:

- [G\*Power](http://www.gpower.hhu.de/) beräknar statistisk power och sampelstorlek för experiment.
- [ESCI (Exploratory Software for Confidence Intervals)](http://www.latrobe.edu.au/psychology/research/research-areas/cognitive-and-developmental-psychology/esci/2001-to-2010) simulerar konfidensintervall, Cohens d, statistisk power m.m. Användbart för planering av studier. Kräver Microsoft Excel.
- [Comprehensive Meta analysis](https://www.meta-analysis.com/) underlättar metaanalyser. Betalprogram, men finns i testversion.
- [Process macro for SPSS and SAS](http://processmacro.org/download.html) är en plugin som underlättar moderator- och medieringsanalys i SPSS och SAS.

### Referenshantering {#refprograms}

Referenshanteringsprogram hjälper dig hålla reda på artiklar, nyheter och andra typer av dokument du samlar på dig under forskningsprocessen.

Jag rekommenderar [Zotero](https://www.zotero.org/). Det är gratis, fungerar tillsammans med Word och har smarta funktioner för import av artiklar.

- [EndNote](http://endnote.com/)
- [JabRef](http://www.jabref.org/)
- [Mendeley](https://www.mendeley.com/)
- [ReadCube Papers](https://www.readcube.com/)
- [Zotero](https://www.zotero.org/)

## Filer {#files}

Nedladdningsbara filer.

| Fil | Beskrivning |
| ------------------ | ---------------------------------------------------------------------- |
| [**diagram-mall.xlsx**](filer/diagram-mall.xlsx) | En mall för Excel med grupperat stapeldiagram, liggande stapeldiagram för Likert-skalor och linjediagram för tidsserier. |
| [**instuderingsfragor-kvantitativ-metod.pdf**](filer/instuderingsfragor-kvantitativ-metod.pdf) | 34 instuderingsfrågor om grundläggande statistik, deskriptiv statistik, inferentiell statistik, survey- och enkätundersökningar samt avslutningsvis bra begrepp att känna till. |
| [**korstabell.xlsx**](filer/korstabell.xlsx) | Visar hur en korstabell (2 rader × 2 kolumner) med antal, kolumnprocent, radprocent och totalprocent ger olika tolkningar. |
| [**korstabell-chi-square.xlsx**](filer/korstabell-chi-square.xlsx) | Visar hur man räknar ut Chi^2^ med observerade och förväntade värden i samma 2 × 2 korstabell. Innehåller även en lista över kritiska Chi^2^-värden. |

Excel-filer är i formatet Excel 2016. Använd filerna precis som du vill, utan några begränsningar.

## Länkar {#links}

### Litteratursökning och litteraturöversikter

- [How to undertake a literature review](http://www.raulpacheco.org/2017/04/how-to-undertake-a-literature-review/)
- [How to (seriously) read a scientific paper](http://www.sciencemag.org/careers/2016/03/how-seriously-read-scientific-paper)
- [How to keep up with the scientific literature](http://www.sciencemag.org/careers/2016/11/how-keep-scientific-literature)

### Frågebatterier

Det finns flera databaser som samlar [frågebatterier inom samhällsvetenskapen](#scales).

### Forskningsmetod

- [Research Methods Knowledge Base](https://www.socialresearchmethods.net/)
- Videoklipp (2 tim): [Kan medierna hantera statistiska undersökningar?](https://www.youtube.com/watch?v=9YVMwlE6s9A)

### Statistik

- [onlinestatbook.com](http://onlinestatbook.com/). Online Statistics Education: An Interactive Multimedia Course of Study. Developed by Rice University, University of Houston Clear Lake, and Tufts University.
- [Andy Fields statisticshell.com](http://www.statisticshell.com/html/limbo.html). Here you can uncover the searing agony of SPSS, the stomach churning fear of central tendency and the rancid bile of z-scores.
- [Seeing Theory - A visual instroduction to probability and statistics](http://students.brown.edu/seeing-theory/).

### Interaktiva guider om statistik

| Guide | Beskrivning |
| ----------------------- | ----------------------------------------------- |
| [Coin Flip Simulator](http://databits.io/bits/coin-flip-simulator) | Om man singlar slant tillräckligt många gånger kommer en binomial distribution att formas. Denna simulering visar hur det ser ut. |
| [Guess the correlation](http://guessthecorrelation.com/) | Spel där du får testa att gissa korrelationen (Pearons r).
| [Interpreting Correlations - an interactive visualization](http://rpsychologist.com/d3/correlation/) | Dra i reglaget för att påverka storleken på korrelationen, och hur korrelationen samvarierar (ursäkta ordvitsen) med variansen. |
| [Rock 'n Polls](http://rocknpoll.graphics/) | Se hur slumpmässigt urval påverkar resultatet av en opinionsundersökning. |
| [Sampling Distribution](http://onlinestatbook.com/stat_sim/sampling_dist/index.html) | Visar effekten av centrala gränsvärdessatsen, och hur stickprovets medelvärde från en distribution av valfri form bildar en normalfördelning. |
| [Simpson's Paradox](http://vudlab.com/simpsons/) | Visar hur [Simpsons paradox](#simpsons-paradox) fungerar i mer detalj, där man kan få helt olika resultat om man analysera all data tillsammans eller gruppvis. |

### Nyhetsartiklar om forskning

- [The one chart you need to understand any health study](https://www.vox.com/2015/1/5/7482871/types-of-study-design)
- [Science Isn’t Broken: It’s just a hell of a lot harder than we give it credit for.](http://fivethirtyeight.com/features/science-isnt-broken/#part1).

### Avancerad statistik

- [Effect Size Calculator](https://www.campbellcollaboration.org/this-is-a-web-based-effect-size-calculator/explore/this-is-a-web-based-effect-size-calculator). Webbtjänst för att beräkna effektstorlekar med konfidensintervall från olika teststatistika.
- [Web Pages that Perform Statistical Calculations!](http://statpages.info/)
- [Free Statistics Calculator](http://www.danielsoper.com/statcalc/default.aspx)
- [VassarStats: Website for Statistical Computation](http://vassarstats.net/)
- [Equivalent Statistics](http://psych.purdue.edu/~gfrancis/EquivalentStatistics/). Konverterar från en teststatistika till en annan.
- [Practical Meta-Analysis Effect Size Calculator](https://www.campbellcollaboration.org/escalc/html/EffectSizeCalculator-SMD-main.php). Beräkna effektstorlekar för metaanalys utifrån N, M och SD (med flera).

### Hantera data

- [How to share data with a statistician](https://github.com/jtleek/datasharing). This is a guide for anyone who needs to share data with a statistician.

## Böcker {#books}

### Nybörjare

- Djurfeldt, G., Larsson, R. & Stjärnhagen, O. (2010). *Statistisk verktygslåda 1: samhällsvetenskaplig orsaksanalys med kvantitativa metoder (2. uppl.)*. Lund: Studentlitteratur.
- Esaiasson, P., Gilljam, M., Oscarsson, H., Towns, A.E. & Wängnerud, L. (2017). *Metodpraktikan: konsten att studera samhälle, individ och marknad (5 uppl.)*. Stockholm: Wolters Kluwer.
- Field, A. P. (2013). *Discovering statistics using IBM SPSS statistics: and sex and drugs and rock “n” roll (4th edition)*. Los Angeles: Sage.

### Avancerad

Frekventism:

- Cohen, J. (1988). *Statistical Power Analysis for the Behavioral Sciences (2nd ed.)*. Hillsdale, N.J: Routledge.
- Mayo, D.G. (1996). *Error and the growth of experimental knowledge*. Chicago: Univ. of Chicago Press.

Bayesiansk statistik:

- Gelman, A. (red.) (2014). *Bayesian data analysis (3rd ed.)*. Boca Raton, Fla.: Chapman & Hall/CRC.

Likelihood:

- Royall, R. M. (1997). *Statistical evidence: A likelihood paradigm (1st ed.)*. London, New York: Chapman & Hall.