# Studieteknik {#study}

Här hittar du:

- Konkreta tips för att plugga bättre
- Vilka tekniker som ger högst inlärning

Studietiden består av en mängd läsande och lärande. Konstigt nog lärs sällan effektivt lärande ut, utan studenter förmodas lära sig detta på egen hand. Därför tänkte jag ge konkreta studietips så att du ska kunna maximera dina resultat.

Är du inte motiverad till att lära dig detta? Tänk då på att de som har högst betyg också tenderar att spendera *mindre* tid på att plugga (Newport, 2016).

## Bästa studieteknikerna

[Dunlosky et al. (2013)](http://doi.org/10.1177/1529100612453266) har sammanfattat litteraturen och rangordnat ett antal studietekniker för att lära sig ny kunskap. De återges i tabellen nedan.

| Studieteknik | Inlärning |
| -------- | --------------- |
| Aktivt testa dina kunskaper | Hög |
| Sprida ut inlärningen över tid | Hög |
| Ställ frågor till dig själv | Medel |
| Förklara för dig själv | Medel |
| Blanda ämnen under dagen (*interleaved practice*) | Medel |
| Läsa sammanfattningar | Låg |
| Markera med understrykningspenna | Låg |
| Komma ihåg nyckelord | Låg |
| Läsa igen | Låg |

Det är i regel bättre att repetera och testa det du lärt dig än att bara försöka läsa effektivt ([Karpicke & Blunt, 2011](http://doi.org/10.1126/science.1199327)). Studera också tillsammans med andra, och ge feedback till varandra. Det ökar också inlärningen ([Sun et al., 2014](http://arxiv.org/abs/1410.3853)).

Skriv ut och läs på papper. Papper är bättre än att läsa på skärm, även om du föredrar skärm ([Singer & Alexander, 2017](https://doi.org/10.1080/00220973.2016.1143794)).

Ta inte med datorn till klassrummet. De som tar med sig datorn får sämre betyg ([Mueller & Oppenheimer, 2014](https://doi.org/10.1177/0956797614524581); [Patterson & Patterson, in press](https://doi.org/10.1016/j.econedurev.2017.02.004)) och presterar sämre ([Ravizza, Uitvlugt, & Fenn, 2017](https://doi.org/10.1177/0956797616677314); [Sana, Weston, & Cepeda, 2013](https://doi.org/10.1016/j.compedu.2012.10.003); [Carter, Greenberg, & Walker, 2017](https://doi.org/10.1016/j.econedurev.2016.12.005)). Lägg mobilen i ett annat rum för bättre studiero ([Ward, Duke, Gneezy, & Bos, 2017](https://doi.org/10.1086/691462)).

Håll en dialog med dig själv, föreställ dig någon som ger motargument och besvara dem. Det leder till djupare förståelse och kunskap ([Zavala & Kuhn, 2017](https://doi.org/10.1177/0956797616689248)).

### Så kan du lägga upp dagen

Tabellen ovan visar enkla saker du kan börja med redan nu. Framför allt bör du planera veckan i förväg, eller åtminstone morgondagen, och se till att aktivt testa dina kunskaper.

En dag kan exempelvis se ut så här:

1. Hårt fokuserat studerande 1-2 timmar, utan internet
2. Paus
3. Återigen 1-2 timmar studerande
4. Paus
5. Studier om 1-2 timmar igen

Sedan är du färdig. Du bör med andra ord studera *mindre* än de 40 timmar per vecka som ofta är riktlinjen vid heltidsstudier. Du bör däremot studera *hårdare* under de timmar du faktiskt studerar.

Därefter bör du inte tänka på studierna alls efter arbetsdagens slut eftersom vila är viktigt. Du minns bättre om du har vila mellan två pass av pluggande ([Mazza et al., 2016](http://doi.org/10.1177/0956797616659930)). Börja sedan morgondagen på samma sätt.

Resultatet av studerandet kan sammanfattas i en formel: <code>kvalitet = tid × intensitet</code>. Åtminstone om vi får tro Newport (2016).

### När du skriver tenta

Enligt Passer (2008, s. 32-33) finns det ett antal saker att tänka på när du sitter och svettas i tentasalen eller på en hemtenta:

- Använd tiden förståndigt. Svara på frågorna du kan först, och frågor som är värda mest poäng. Om du inte kan en fråga, gör den sist.
- På hemtentor eller längre skrivuppgifter, gör först en outline i punktform. Skriv sedan.
- Om du fyller i kryssrutor, försök att svara på frågan innan du ser svarsalternativen. Om du hittar ditt svar bland alternativen, kryssa i det.
- Om du fyller i kryssrutor och ändrar ditt svar så gör du troligen rätt. Byt svarsalternativ om du är tämligen säker.

## Öka din motivation

Vänta inte på att din motivation ska komma. Försök skapa motivation i stället.

Psykologifabriken ger [sju tips](http://www.psykologifabriken.se/boosta-din-motivation-med-sju-enkla-knep/):

1. **Jobba mot tydligt mål**. Vad vill du uppnå? När ska målet var uppnåt? Hur vet du när målet är uppnåt? Ju mer konkret du är, desto lättare är det att nå ett mål. Undvik vaga mål.

2. **Bl inte riktigt färdig**. Om du inte riktigt avslutar ett projekt, är det lättare att komma igång med det nästa gång. Det beror på att avslutade projekt är lättare att komma ihåg. Det kallas [Zeigarnik-effeten](http://changingminds.org/explanations/memory/zeigarnik_effect.htm).

3. **Sätt startdatum**. Vi är mer benägna att lyckas med att ändra beteende om det finns en tydlig startpunkt. Startpunkten kan vara helt godtycklig.

4. **Gör tråkigaste först**. Då blir det mer belönande ju mer du jobbar. Läs den tråkigaste eller jobbigaste boken först.

5. **Ge dig belöningar**. Ge dig själv många små belöningar när du har pluggat. Det bygger på positiv förstärkning och ökar sannolikheten att du fortsätter.

6. **Kombinera nytta med nöje**. Det som vållgar obehag eller är tråkigt undviker vi. Försök därför att kombinera pluggandet med något som är roligt. Lyssna på en ljudbok samtidigt som du tränar, läs kurslitteratur samtidigt som du åker på resa.

7. **Sätt flera delmål**. Det ska inte krävas mycket för att nå ett mål. Ju längre bort målet är, desto lättare ger vi upp. Det beror på att vi ställer för höga krav på oss själva. Sänk målen och gör flera delmål i stället. Det bör vara lätt att nå ditt första delmål. Läs tio sidor och ge dig själv en belöning.

## Hålla reda på referenser

Ett program för referenshantering hjälper dig att hålla reda på artiklar, nyhetsartiklar och andra typer av dokument du samlar på dig.

Jag rekommenderar [Zotero](https://www.zotero.org/). Det är gratis, fungerar tillsammans med Word och har smarta funktioner för import av artiklar.

Det finns dock [fler referenshanteringsprogram](#refprograms).

## Gör bättre sökningar på Google

Videoklipp (8 min) om hur du söker bättre på Google: [How to Get Better Search Results](https://www.youtube.com/watch?v=U9TNmomU7l0).

<iframe src="https://www.youtube.com/embed/U9TNmomU7l0?rel=0" frameborder="0" class="mediaplayer videoplayer" allowfullscreen></iframe>

Se också: [Google: Alla tips och knep](http://www.google.com/intl/sv_se/insidesearch/tipstricks/all.html).

## Skriva litteraturöversikter

- [How to undertake a literature review](http://www.raulpacheco.org/2017/04/how-to-undertake-a-literature-review/)

## Referenser

- Carter, S. P., Greenberg, K., & Walker, M. S. (2017). [The impact of computer usage on academic performance: Evidence from a randomized trial at the United States Military Academy](https://doi.org/10.1016/j.econedurev.2016.12.005). *Economics of Education Review, 56*(Supplement C), 118–132.
- Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). [Improving Students’ Learning With Effective Learning Techniques: Promising Directions From Cognitive and Educational Psychology](http://doi.org/10.1177/1529100612453266). *Psychological Science in the Public Interest, 14*(1), 4–58.
- Karpicke, J. D., & Blunt, J. R. (2011). [Retrieval Practice Produces More Learning than Elaborative Studying with Concept Mapping](http://doi.org/10.1126/science.1199327). *Science, 331*(6018), 772–775. 
- Mazza, S., Gerbier, E., Gustin, M.-P., Kasikci, Z., Koenig, O., Toppino, T. C., & Magnin, M. (2016). [Relearn Faster and Retain Longer Along With Practice, Sleep Makes Perfect](http://doi.org/10.1177/0956797616659930). *Psychological Science*, 956797616659930.
- Mueller, P. A., & Oppenheimer, D. M. (2014). [The Pen Is Mightier Than the Keyboard: Advantages of Longhand Over Laptop Note Taking](https://doi.org/10.1177/0956797614524581). *Psychological Science, 25*(6), 1159–1168.
- Newport, C. (2016). *Deep Work: Rules for Focused Success in a Distracted World*. Piatkus Books.
- Passer, M. W. (2008). *Psychology: The Science of Mind and Behavior (4th ed.)*. London: McGraw-Hill Higher Education.
- Patterson, R. W., & Patterson, R. M. (in press). [Computers and Productivity: Evidence from Laptop Use in the College Classroom](https://doi.org/10.1016/j.econedurev.2017.02.004). *Economics of Education Review*.
- Ravizza, S. M., Uitvlugt, M. G., & Fenn, K. M. (2017). [Logged In and Zoned Out](https://doi.org/10.1177/0956797616677314). *Psychological Science, 28*(2), 171–180.
- Sana, F., Weston, T., & Cepeda, N. J. (2013). [Laptop multitasking hinders classroom learning for both users and nearby peers](https://doi.org/10.1016/j.compedu.2012.10.003). *Computers & Education, 62*(Supplement C), 24–31.
- Singer, L. M., & Alexander, P. A. (2017). [Reading Across Mediums: Effects of Reading Digital and Print Texts on Comprehension and Calibration](https://doi.org/10.1080/00220973.2016.1143794). *The Journal of Experimental Education, 85*(1), 155–172.
- Sun, D. L., Harris, N., Walther, G., & Baiocchi, M. (2014). [Peer assessment enhances student learning](http://arxiv.org/abs/1410.3853). *arXiv:1410.3853 [Physics, Stat]*.
- Ward, A. F., Duke, K., Gneezy, A., & Bos, M. W. (2017). Brain Drain: The Mere Presence of One’s Own Smartphone Reduces Available Cognitive Capacity. *[Journal of the Association for Consumer Research](https://doi.org/10.1086/691462), 2*(2), 140–154.
- Zavala, J., & Kuhn, D. (2017). [Solitary Discourse Is a Productive Activity](https://doi.org/10.1177/0956797616689248). *Psychological Science*.